#!/bin/sh

#
# Copyright 2015 Basho Technologies Inc
#
# Shell script for starting the Python Spark Shell REPL with Riak Spark Connector

CUR_DIR=`pwd`
EXTRA_CP=$(echo $CUR_DIR/**/*.jar | tr ' ' ':'):
EXTRA_JRS=$(echo $CUR_DIR/**/*.jar | tr ' ' ',')

. ./config.sh

pyspark --driver-class-path $EXTRA_CP \
	--jars  $EXTRA_JRS\
	--conf spark.riak.connection.host=$RIAK_HOST:$RIAK_PORT \
	$@
