#!/bin/sh

#
# Copyright 2015 Basho Technologies Inc
#
# Shell script for starting the IPython Spark  with Riak Spark Connector

. ./config.sh

IPYTHON_OPTS='notebook' ./rpyspark-shell --driver-memory $DRIVER_MEM
