/*
  * Copyright 2015 Basho Technologies Inc
  *
  * Riak Spark Shell defaults
  */

// Generated by http://patorjk.com/software/taag/#p=display&f=Small%20Slant&t=%20Riak%20%2B%20Spark
println("Welcome again, this time with taste of\n" +
  "     ___  _      __       __    ____              __  \n" +
  "    / _ \\(_)__ _/ /__  __/ /_  / __/__  ___ _____/ /__\n" +
  "   / , _/ / _ `/  '_/ /_  __/ _\\ \\/ _ \\/ _ `/ __/  '_/\n" +
  "  /_/|_/_/\\_,_/_/\\_\\   /_/   /___/ .__/\\_,_/_/ /_/\\_\\ \n" +
  "                                /_/                   \n")

print("Spark With Riak Connector (Riak " + sc.getConf.get("spark.riak.connection.host") + ")\n" +
  "(Riak address might be changed by editing param in rspark)\n\n" +

  "To load & run demo (it requires to stop the existing SparkContext)\n" +
  "    :load demo/<demo-name>.scala\n" +
  "    <demo-name>.main(Array())\n\n")

import com.basho.spark.connector.demos.Demo2iConfig
import com.basho.spark.connector._
