#!/bin/sh

#
# Copyright 2015 Basho Technologies Inc
#
# Shell script for submitting Riak Spark Connector Demos

#	--properties-file ./simpledemo.properties \
spark-submit --jars $(echo ./lib/*.jar | tr ' ' ',') \
	--conf spark.riak.connection.host=127.0.0.1:10017 \
	--class com.basho.spark.connector.demos.FootballDemo \
	--driver-memory 4G \
	$@ \
	$(echo ./demos-jar/*.jar | tr ' ' ',')
