#!/bin/sh

#
# Copyright 2015 Basho Technologies Inc
#
# Shell script for submitting Riak Spark Connector Demos

. ./config.sh

spark-submit --jars $(echo ./lib/*.jar | tr ' ' ',') \
	--master $MASTER_URL \
	--conf spark.riak.connection.host=$RIAK_HOST:$RIAK_PORT \
	--class $MAIN_CLASS \
	--driver-memory $DRIVER_MEM \
	--executor-memory $EXECUTOR_MEM \
	$@ \
	$(echo ./examples-jar/*.jar | tr ' ' ',')
