#!/bin/sh

#
# Copyright 2015 Basho Technologies Inc
#
# Shell script for starting the Spark Shell REPL with Riak Spark Connector

. ./config.sh

spark-shell --jars $(echo ./**/*.jar | tr ' ' ',') \
	--conf spark.riak.connection.host=$RIAK_HOST:$RIAK_PORT \
	-i ./rspark-shell-defaults.scala \
	$@
